name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    container:
      image: howardlau1999/yatcpu-autograder:base
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: SBT Test
        run: sbt test
